### ISSUE TITLE
libGDX ImageView upside-down

### ISSUE THREAD

**Issue by nooone** [Trixt0r/LibGDX-FX#2]
I have the issue that the stuff that libGDX renders to the ImageView gets displayed upside-down. The input seems to be correctly though, but it just doesn't match the visuals. Any idea how to fix this?

**Comment by Trixt0r** [comment]
Can you tell me, how you set up the camera and stuff? I guess this is again a graphics card thingy...

**Comment by nooone** [comment]
I'm using the latest libgdx version 1.2.1-SNAPSHOT. I have three cases: once a OrthogonalCamera which renders a sprite, another Stage with an OrthogonalCamera which is completely default and a PerspectiveCamera which is used to render 3D models. All of this code is actually code from my game and when calling it from the standard desktop project (i.e. pure lwjgl backend) it's not upside down.
